swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: doc-controller
    description: Doc Controller
paths:
  '/document/call/{id}':
    get:
      tags:
        - doc-controller
      summary: restCall
      operationId: restCallUsingGET
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Doc'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/document/delete/{id}':
    delete:
      tags:
        - doc-controller
      summary: deleteDoc
      operationId: deleteDocUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            type: integer
            format: int64
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
  '/document/get/{id}':
    get:
      tags:
        - doc-controller
      summary: getDocument
      operationId: getDocumentUsingGET
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Doc'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /document/post:
    post:
      tags:
        - doc-controller
      summary: postDoc
      operationId: postDocUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: doc
          description: doc
          required: true
          schema:
            $ref: '#/definitions/Doc'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Doc'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /document/put:
    put:
      tags:
        - doc-controller
      summary: putDoc
      operationId: putDocUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: doc
          description: doc
          required: true
          schema:
            $ref: '#/definitions/Doc'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Doc'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  Doc:
    type: object
    properties:
      author:
        type: string
      id:
        type: integer
        format: int64
      text:
        type: string
      title:
        type: string
    title: Doc
